[package]
name = "simple_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
etcd-client = "0.10.2"
tls = "0.0.3"
tokio = "1.21.2"
