apiVersion: v1
kind: Service
metadata:
  name: simpleweb-service
spec:
  type: NodePort
  selector:
    app: simpleweb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb-deployment
  labels:
    app: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        env:
          - name: OUT
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        imagePullPolicy: Never
        image: simpleweb
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: simpleweb-etcd
  name: simpleweb-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleweb-etcd
  serviceName: simpleweb-etcd
  template:
    metadata:
      labels:
        app: simpleweb-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          imagePullPolicy: IfNotPresent
          command:
          - /usr/local/bin/etcd
          args:
          - "--listen-client-urls"
          - "http://0.0.0.0:2388"
          - "--advertise-client-urls"
          - "http://simpleweb-etcd-0:2388"
          - "--listen-peer-urls"
          - "http://0.0.0.0:2389"
          - "--initial-advertise-peer-urls"
          - "http://simpleweb-etcd-0:2389"
          - "--listen-metrics-urls"
          - "http://0.0.0.0:2379"
          - "--name"
          - "simpleweb-etcd"
          - "--max-txn-ops"
          - "999999"
          - "--auto-compaction-mode"
          - periodic
          - "--auto-compaction-retention"
          - 1m
          - "--snapshot-count"
          - "10000"
          env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "1"
          ports:
          - containerPort: 2389
            name: peer
            protocol: TCP
          - containerPort: 2388
            name: client
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb-etcd
  labels:
    app: simpleweb-etcd
spec:
  ports:
  - port: 2388
    name: client
  - port: 2389
    name: peer
  selector:
    app: simpleweb-etcd



