apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: simpleweb-service
spec:
  type: NodePort
  selector:
    app: simpleweb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: simpleweb-deployment
  labels:
    app: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        volumeMounts:
        - mountPath: /etc/my/certs
          name: tls-assets
          readOnly: true
        env:
          - name: OUT
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        imagePullPolicy: Never
        image: simpleweb
        ports:
        - containerPort: 8080
      volumes: 
      - name: tls-assets
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: simpleweb-secret-cert
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: simpleweb-etcd
spec:
  selector:
    component: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379

